<div class="form-group" ng-class="{'has-error': formData.errors.length, 'has-feedback': formData.errors.length}">
    <div class="col-sm-2">
        <i ng-if="formData.options.description.length" class="fa fa-question-circle" uib-popover="{{ formData.options.description }}"></i>
    </div>
    <div class="col-sm-10">
        <div class="checkbox">
            <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
            <label class="i-checks">
                <input type="checkbox" ng-model="model" ng-change="onChange()"><i></i>{{ formData.label }}
            </label>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
