<div class="form-group" ng-class="{'has-error': formData.errors.length, 'has-feedback': formData.errors.length}">
    <label class="col-sm-2 control-label">
        <i ng-if="formData.options.description.length" class="fa fa-question-circle" uib-popover="{{ formData.options.description }}"></i>
        <abbr ng-if="formData.required" title="">*</abbr>
        {{ formData.label }}
    </label>
    <div class="col-sm-10">
        <div class="input-group w-md">
            <input type="hidden" name="{{ formData.name }}" value="{{ value | date:'yyyy-MM-dd' }}">
            <input
                type="hidden"
                ng-model="value"
                uib-datepicker-popup="yyyy-MM-dd"
                is-open="popup.opened"
                datepicker-options="dateOptions"
            >
            <input type="text" class="form-control" value="{{ value | datetime:'':'YYYY-MM-DD'}}" disabled>
            <span class="input-group-btn">
                <button type="button" class="btn" ng-class="{'btn-default': !formData.errors.length, 'btn-danger': formData.errors.length}" ng-click="open($event)">
                    <i class="fa fa-calendar"></i>
                </button>
            </span>
        </div>
        <span ng-if="formData.errors.length" class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
