<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-3 col-md-2 control-label">
        <div class="pull-left hidden-sm hidden-xs">
            <span class="fa fa-fw text-danger" ng-class="{'fa-exclamation-triangle': formData.errors.length}"></span>
            <a ng-show="formData.value" class="text-light" ng-click="empty()">
                <i class="fa fa-fw fa-trash"></i>
            </a>
        </div>
        <div class="pull-right">
            <a class="text-muted" ng-if="formData.description != null" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
                <i class="fa fa-question-circle"></i>
            </a>
            <label>{{ formData.label }}</label>
            <span ng-if="formData.required">*</span>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="col-sm-9 col-md-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <div>
            <div class="pull-left">
                <input
                    type="hidden"
                    ng-model="date"
                    uib-datepicker-popup="yyyy-MM-dd"
                    is-open="popup.opened"
                    datepicker-options="dateOptions"
                >
                <div class="input-group w-md">
                    <input type="text" class="form-control" value="{{ date | datetime:'':'YYYY-MM-DD'}}" disabled>
                    <span class="input-group-btn">
                        <button type="button" class="btn" ng-class="{'btn-default': !formData.errors.length, 'btn-danger': formData.errors.length}" ng-click="open($event)">
                            <i class="fa fa-calendar"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="pull-left m-l-md">
                <div uib-timepicker ng-model="time" show-spinners="false" show-meridian="false"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
