<div ng-if="formData.showLabel" class="form-group">
    <div class="col-sm-4 col-md-3 control-label">
        <span class="pointer"
              ng-if="formData.collapseAble"
              ng-click="formData.collapse = !formData.collapse"
              ng-class="{'text-danger' : formData.errors.length}">
            <i class="fa fa-fw"
               ng-class="{'fa-chevron-down': !formData.collapse, 'fa-chevron-right': formData.collapse}"></i>
            {{ formData.label }}
        </span>
        <span ng-if="!formData.collapseAble" ng-class="{'text-danger' : formData.errors.length}">
            {{ formData.label }}
        </span>
        <i class="fa fa-fw text-danger pull-left" ng-class="{'fa-exclamation-triangle': formData.errors.length}"></i>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
        </div>
        <div ng-if="formData.errors.length" class="form-control-static text-danger">
            Fieldset contains errors
        </div>
    </div>
</div>

<fieldset uib-collapse="formData.collapse">
    <ng-include ng-repeat="element in elements" src="element.template"></ng-include>
</fieldset>
