<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-4 col-md-3 control-label">
        <label for="{{ formData.id }}" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
            <i class="fa fa-fw fa-question-circle-o text-muted" ng-if="formData.description != null"></i>
            {{ formData.label }}
            <span ng-if="formData.required">*</span>
        </label>
        <i class="fa fa-fw text-danger pull-left" ng-if="formData.errors.length"
           ng-class="{'fa-exclamation-triangle': formData.errors.length}"></i>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
            <button type="button" class="btn btn-link" ng-show="formData.value.length > 0 && !formData.readonly"
                    ng-click="empty()">
                <i class="fa fa-fw fa-times"></i>
            </button>
        </div>
        <div class="input-group">
            <span class="input-group-addon">
                <i class="fa fa-fw fa-file"></i>
            </span>
            <input ng-if="formData.multiple!==true" id="{{ formData.id }}" type="file" name="{{ formData.name }}"
                   class="form-control" ng-model="formData.value" ng-disabled="formData.readonly">
            <input ng-if="formData.multiple===true" id="{{ formData.id }}" type="file" name="{{ formData.name }}"
                   class="form-control" ng-model="formData.value" ng-disabled="formData.readonly" multiple="multiple">
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
