<input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
<div ng-if="formData.staticControl" class="form-group">
    <div class="col-sm-4 col-md-3 control-label">
        <a class="text-muted" ng-if="formData.description != null" uib-popover="{{ formData.description }}"
           popover-trigger="'mouseenter'">
            <i class="fa fa-fw fa-question-circle-o"></i>
        </a>
        <label>{{ formData.label }}</label>
        <span ng-if="formData.required">*</span>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <p class="form-control-static">{{ formData.staticControlText }}</p>
    </div>
</div>
