<div class="form-group" ng-class="{'has-error': formData.errors.length, 'has-feedback': formData.errors.length}">
    <label class="col-sm-2 control-label">
        <abbr ng-if="formData.required" title="">*</abbr>
        {{ formData.label }}
    </label>
    <div class="col-sm-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ linkData.linkId }}">
        <div class="input-group">
            <input type="text" class="form-control" value="{{ linkData.linkDisplayName }}" readonly>
            <span class="input-group-btn">
                <a type="button" class="btn btn-default" ng-click="selectLink()">
                    <i class="fa fa-check"></i>
                    <?= $this->translate('button.select', 'admin') ?>
                </a>
                <a ng-show="linkData.previewUrl" target="_blank" class="btn btn-default" ng-href="{{ getUrl() }}">
                    <i class="fa fa-mail-forward"></i>
                    <?= $this->translate('button.preview', 'admin') ?>
                </a>
            </span>
        </div>
        <span ng-if="formData.errors.length" class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
