<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-4 col-md-3 control-label">
        <label uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
            <i class="fa fa-fw fa-question-circle-o text-muted" ng-if="formData.description != null"></i>
            {{ formData.label }}
            <span ng-if="formData.required">*</span>
        </label>
        <i class="fa fa-fw text-danger pull-left" ng-if="formData.errors.length"
           ng-class="{'fa-exclamation-triangle': formData.errors.length}"></i>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
            <button type="button" class="btn btn-link" ng-show="formData.value.linkId && !formData.readonly"
                    ng-click="empty()">
                <i class="fa fa-fw fa-times"></i>
            </button>
        </div>
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value.linkId }}">
        <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn btn-default" ng-click="selectLink()" ng-disabled="formData.readonly"
                        uib-popover="<?= $this->translate('button.select', 'admin') ?>" popover-trigger="'mouseenter'">
                    <i class="fa fa-fw fa-chain text-info"></i>
                </button>
                <a ng-show="linkData.previewUrl" target="_blank" class="btn btn-default" ng-href="{{ getUrl() }}"
                   uib-popover="<?= $this->translate('button.preview', 'admin') ?>" popover-trigger="'mouseenter'">
                    <i class="fa fa-fw fa-link-external"></i>
                </a>
            </span>
            <input type="text" class="form-control" value="{{ formData.value.linkDisplayName }}" disabled>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
