<div class="modal-header">
    <h3 class="modal-title"><?= $this->translate('title.link', 'admin') ?></h3>
</div>
<div class="modal-body modal-scroll-body">
    <div class="container-fluid">
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    <?= $this->translate('label.link-type-selector', 'admin') ?>
                </label>
                <div class="col-sm-10">
                    <select ng-model="linkData.linkType" class="form-control" ng-change="change()">
                        <option ng-repeat="(type, label) in availableLinkTypes" value="{{type}}">{{label}}</option>
                    </select>
                </div>
            </div>
            <hr>
            <div ng-repeat="item in includeArray">
                <div ng-include="item"></div>
            </div>
        </form>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-click="ok()">
        <span class="fa fa-check"></span>
        <?= $this->translate('button.save', 'admin') ?>
    </button>
    <button class="btn btn-default" ng-click="cancel()"><?= $this->translate('button.cancel', 'admin') ?></button>
</div>
