<div class="form-group">
    <label class="col-sm-2 control-label">
        <i ng-if="formData.options.description.length" class="fa fa-question-circle" uib-popover="{{ formData.options.description }}"></i>
        <abbr ng-if="formData.required" title="">*</abbr>
        {{ formData.label }}
    </label>
    <div class="col-sm-10" ng-class="{'has-error': formData.errors.length}">
        <input ng-repeat="value in values" type="hidden" name="{{ formData.name }}[]" value="{{value}}">
        <div ng-repeat="option in options">
            <label class="i-checks">
                <input ng-model="checkboxModel[option.id]" type="checkbox" ng-change="select()">
                <i></i>{{ option.label }}
            </label>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
