<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-4 col-md-3 control-label">
        <label for="{{ formData.id }}" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
            <i class="fa fa-fw fa-question-circle-o text-muted" ng-if="formData.description != null"></i>
            {{ formData.label }}
            <span ng-if="formData.required">*</span>
        </label>
        <i class="fa fa-fw text-danger pull-left" ng-if="formData.errors.length"
           ng-class="{'fa-exclamation-triangle': formData.errors.length}"></i>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
            <button type="button" class="btn btn-link" ng-show="values.length > 0 && !formData.readonly"
                    ng-click="empty()">
                <i class="fa fa-fw fa-times"></i>
            </button>
        </div>
        <input ng-if="values.length == 0" type="hidden" name="{{ formData.name }}" value="">
        <input ng-repeat="value in values" type="hidden" name="{{ formData.name }}[]" value="{{value}}">
        <div class="checkbox" ng-repeat="option in options">
            <label class="i-checks">
                <input ng-model="checkboxModel[option.id]" type="checkbox" ng-change="select()"
                       ng-keydown="preventEnter($event)" ng-keypress="preventEnter($event)"
                       ng-keyup="preventEnter($event)">
                <i></i>{{ option.label }}
            </label>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
