<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-4 col-md-3 control-label">
        <label for="{{ formData.id }}" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
            <i class="fa fa-fw fa-question-circle-o text-muted" ng-if="formData.description != null"></i>
            {{ formData.label }}
            <span ng-if="formData.required">*</span>
        </label>
        <i class="fa fa-fw text-danger pull-left" ng-if="formData.errors.length"
           ng-class="{'fa-exclamation-triangle': formData.errors.length}"></i>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
            <button type="button" class="btn btn-link" ng-show="formData.value.length > 0 && !formData.readonly"
                    ng-click="empty()">
                <i class="fa fa-fw fa-times"></i>
            </button>
        </div>
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <div class="input-group">
            <span class="input-group-addon">
                <span class="fa fa-fw fa-lock"></span>
            </span>
            <input id="{{ formData.id }}" type="{{ getInputType() }}" class="form-control" ng-model="formData.value"
                   ng-disabled="formData.readonly" ng-keydown="preventEnter($event)" ng-keypress="preventEnter($event)"
                   ng-keyup="preventEnter($event)">
            <span class="input-group-btn">
                <button type="button" class="btn btn-default" ng-click="togglePassword()">
                    <i class="fa fa-fw fa-eye" ng-class="{'text-danger': showPassword, 'text-info': !showPassword}"></i>
                </button>
            </span>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
