<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-3 col-md-2 control-label">
        <div class="pull-left hidden-sm hidden-xs">
            <span class="fa fa-fw text-danger" ng-class="{'fa-exclamation-triangle': formData.errors.length}"></span>
            <a ng-show="formData.value.length > 0" class="text-light" ng-click="empty()">
                <i class="fa fa-fw fa-trash"></i>
            </a>
        </div>
        <div class="pull-right">
            <a class="text-muted" ng-if="formData.description != null" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
                <i class="fa fa-question-circle"></i>
            </a>
            <label for="{{ formData.id }}">{{ formData.label }}</label>
            <span ng-if="formData.required">*</span>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="col-sm-9 col-md-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <div class="input-group">
            <input id="{{ formData.id }}" type="{{ getInputType() }}" class="form-control" ng-model="formData.value" ng-disabled="formData.readonly" ng-keydown="preventEnter($event)" ng-keypress="preventEnter($event)" ng-keyup="preventEnter($event)">
            <span class="input-group-btn">
                <button type="button" class="btn" ng-class="{'btn-warning': showPassword, 'btn-default': !showPassword}" ng-click="togglePassword()"><i class="fa fa-eye"></i></button>
            </span>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
