<div class="form-group" ng-class="{'has-error': formData.errors.length, 'has-feedback': formData.errors.length}">
    <div class="col-sm-2 control-label">
        <i ng-if="formData.options.description.length" class="fa fa-question-circle" uib-popover="{{ formData.options.description }}"></i>
        <abbr ng-if="formData.required" title="">*</abbr>
        {{ formData.label }}
    </div>
    <div class="col-sm-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <div class="checkbox" ng-repeat="option in options">
            <label>
                <input name="{{ formData.id }}" ng-model="radioModel" type="radio" ng-value="option.id" ng-change="select(radioModel)">
                {{ option.label }}
            </label>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
