<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-4 col-md-3 control-label">
        <label uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
            <i class="fa fa-fw fa-question-circle-o text-muted" ng-if="formData.description != null"></i>
            {{ formData.label }}
            <span ng-if="formData.required">*</span>
        </label>
        <i class="fa fa-fw text-danger pull-left" ng-if="formData.errors.length"
           ng-class="{'fa-exclamation-triangle': formData.errors.length}"></i>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
            <button type="button" class="btn btn-link" ng-show="notEmpty() && !formData.readonly" ng-click="empty()">
                <i class="fa fa-fw fa-times"></i>
            </button>
        </div>
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <ui-select ng-model="formData.valueOption.selected" ng-disabled="formData.readonly" reset-search-input="false"
                   search-enabled="searchEnabled" on-select="select($item, $model)">
            <ui-select-match placeholder="{{ label }}">
                {{$select.selected.label}}
            </ui-select-match>
            <ui-select-choices repeat="option in formData.valueOptions | filter: $select.search">
                <div ng-bind-html="option.label | highlight: $select.search"></div>
            </ui-select-choices>
        </ui-select>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
