<div class="form-group" ng-class="{'has-error': errorMessages.length, 'has-feedback': errorMessages.length}">
    <label for="{{ formData.id }}" class="col-sm-2 control-label">
        <abbr ng-if="formData.required" title="">*</abbr>
        {{ formData.label }}
    </label>
    <div class="col-sm-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ option.selected.id }}">
        <ui-select ng-model="option.selected" reset-search-input="false" search-enabled="true">
            <ui-select-match placeholder="{{ label }}">
                {{$select.selected.label}}
            </ui-select-match>
            <ui-select-choices repeat="option in options | filter: $select.search">
                <div ng-bind-html="option.label | highlight: $select.search"></div>
            </ui-select-choices>
        </ui-select>
        <span ng-if="formData.errors.length" class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
