<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <label for="{{ formData.id }}" class="col-sm-2 control-label">
        <i ng-if="formData.options.description.length" class="fa fa-question-circle" uib-popover="{{ formData.options.description }}"></i>
        <abbr ng-if="formData.required" title="">*</abbr>
        {{ formData.label }}
    </label>
    <div class="col-sm-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <ui-select ng-model="option.selected" reset-search-input="false" search-enabled="searchEnabled" on-select="select($item, $model)">
            <ui-select-match placeholder="{{ label }}">
                {{$select.selected.label}}
            </ui-select-match>
            <ui-select-choices repeat="option in options | filter: $select.search">
                <div ng-bind-html="option.label | highlight: $select.search"></div>
            </ui-select-choices>
        </ui-select>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
