<div class="line line-dashed b-b line-lg"></div>
<button class="btn btn-xs btn-default m-b-sm" type="button" ng-click="startSortingMode()" ng-show="elements.length > 0">
    Start Sorting
</button>
<fieldset ui-tree data-drag-enabled="sortingMode" data-max-depth="1" data-empty-placeholder-enabled="false">
    <div ui-tree-nodes="" ng-model="elements">
        <div ui-tree-node ng-repeat="element in elements track by $index" data-collapsed="false">
            <div class="panel panel-default" ng-class="{'marked-deleted' : element.deleted}">
                <div class="panel-heading">
                    <input type="hidden" name="{{ element.formName }}[__index__]" value="{{ $index }}">
                    <input type="hidden" name="{{ element.formName }}[__name__]" value="{{ element.name }}">
                    <input type="hidden" name="{{ element.formName }}[__deleted__]" value="{{ element.deleted }}">
                    <input type="hidden" name="{{ element.formName }}[__type__]" value="{{ element.type }}">
                    <div class="row">
                        <div class="col-xs-6" ng-show="sortingMode">
                            <?php if ($this->permission('admin42')->isGranted('dynamic/manage/sort')): ?>
                                <a class="btn btn-xs btn-info" ui-tree-handle>
                                    <i class="fa fa-fw fa-sort"></i>
                                </a>
                            <?php endif; ?>
                            <span ng-show="element.name.length > 0">
                                {{ element.name }}
                            </span>
                            <span class="text-muted" ng-hide="element.name.length > 0">
                                <?= $this->translate('stack.no-name', 'admin')?>
                            </span>
                            <small class="text-muted">
                                - {{ element.type }}
                            </small>
                        </div>
                        <div class="col-xs-6" ng-hide="sortingMode">
                            <div ng-hide="element.nameEditing">
                                <a class="btn btn-link btn-xs" ng-click="element.collapsed = !element.collapsed">
                                    <i class="fa fa-fw" ng-class="{'fa-chevron-down': !element.collapsed, 'fa-chevron-right': element.collapsed}"></i>
                                </a>
                                <a ng-click="element.nameEditing = true" ng-show="element.name.length > 0">
                                    {{ element.name }}
                                </a>
                                <a ng-click="element.nameEditing = true" class="text-muted" ng-hide="element.name.length > 0">
                                    <?= $this->translate('stack.no-name', 'admin')?>
                                </a>
                                <small class="text-muted">
                                    - {{ element.type }}
                                </small>
                            </div>
                            <div ng-show="element.nameEditing">
                                <div class="input-group input-group-sm">
                                    <input type="text" ng-model="element.name" class="form-control" placeholder="<?= $this->translate('stack.no-name', 'admin')?>">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button" ng-click="element.nameEditing = false">
                                            <i class="fa fa-check"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-6 text-right">
                            <?php if ($this->permission('admin42')->isGranted('dynamic/manage/delete')): ?>
                                <button class="btn btn-xs btn-danger" type="button" ng-click="element.deleted = !element.deleted">
                                <span ng-show="element.deleted" class="fa-stack">
                                    <i class="fa fa-fw fa-trash fa-stack-1x"></i>
                                    <i class="fa fa-fw fa-ban fa-stack-2x"></i>
                                </span>
                                    <i ng-hide="element.deleted" class="fa fa-fw fa-trash"></i>
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div uib-collapse="element.collapsed" class="panel-body">
                    <ng-include src="element.template"></ng-include>
                </div>
            </div>
        </div>
    </div>
</fieldset>
<?php if ($this->permission('admin42')->isGranted('dynamic/manage/add')): ?>
    <div class="form-group">
        <div class="col-sm-offset-9 col-sm-2 text-right">
            <select ng-if="protoTypes.length > 1" class="form-control" ng-model="data.selectedProtoType" ng-options="prototype.label for prototype in protoTypes"></select>
        </div>
        <div class="col-sm-1 text-right">
            <button class="btn btn-default" ng-click="addTemplate()" type="button">
                <?= $this->translate('button.add', 'admin')?>
            </button>
        </div>
    </div>
<?php endif; ?>
<div class="line line-dashed b-b line-lg pull-in"></div>
