<div class="form-group" ng-class="{'has-error': formData.errors.length, 'has-feedback': formData.errors.length}">
    <label class="col-sm-2 control-label">
        <i ng-if="formData.options.description.length" class="fa fa-question-circle" uib-popover="{{ formData.options.description }}"></i>
        {{ formData.label }}
    </label>
    <div class="col-sm-10">
        <div>
            <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
            <label class="i-switch m-t-xs m-r bg-primary">
                <input type="checkbox" ng-model="model" ng-change="onChange()"><i></i>
            </label>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
