<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-3 col-md-2 control-label">
        <div class="pull-left hidden-sm hidden-xs">
            <span class="fa fa-fw text-danger" ng-class="{'fa-exclamation-triangle': formData.errors.length}"></span>
            <a ng-show="formData.value.length > 0" class="text-light" ng-click="empty()">
                <i class="fa fa-fw fa-trash"></i>
            </a>
        </div>
        <div class="pull-right">
            <a class="text-muted" ng-if="formData.description != null" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
                <i class="fa fa-question-circle"></i>
            </a>
            <label for="{{ formData.id }}">{{ formData.label }}</label>
            <span ng-if="formData.required">*</span>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="col-sm-9 col-md-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <div class="row">
            <div ng-if="formData.value" class="col-sm-4">
                <div class="videoWrapper">
                    <iframe ng-src="{{ videoUrl() }}" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
            <div ng-class="{'col-sm-8': formData.value, 'col-sm-12': !formData.value}">
                <input type="text" class="form-control" id="{{ formData.id }}" ng-model="youtubeLink" ng-change="changeValue()" ng-readonly="formData.readonly" ng-keydown="preventEnter($event)" ng-keypress="preventEnter($event)" ng-keyup="preventEnter($event)">
            </div>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
