<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-4 col-md-3 control-label">
        <label for="{{ formData.id }}" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
            <i class="fa fa-fw fa-question-circle-o text-muted" ng-if="formData.description != null"></i>
            {{ formData.label }}
            <span ng-if="formData.required">*</span>
        </label>
        <i class="fa fa-fw text-danger pull-right" ng-if="formData.errors.length"
           ng-class="{'fa-exclamation-triangle': formData.errors.length}"></i>
    </div>
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
            <button type="button" class="btn btn-link" ng-show="formData.value.length > 0 && !formData.readonly"
                    ng-click="empty()">
                <i class="fa fa-fw fa-times"></i>
            </button>
        </div>
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <div class="input-group">
            <span class="input-group-addon">
                <i class="fa fa-fw fa-youtube"></i>
            </span>
            <input type="text" class="form-control" id="{{ formData.id }}" ng-model="youtubeLink"
                   ng-change="changeValue()" ng-readonly="formData.readonly" ng-keydown="preventEnter($event)"
                   ng-keypress="preventEnter($event)" ng-keyup="preventEnter($event)">
        </div>
        <div ng-if="formData.value" class="embed-responsive embed-responsive-16by9">
            <div class="videoWrapper">
                <iframe class="embed-responsive-item" ng-src="{{ videoUrl() }}" frameborder="0"
                        allowfullscreen></iframe>
            </div>
        </div>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
