<div class="form-group" ng-class="{'has-error': formData.errors.length, 'has-feedback': formData.errors.length}">
    <label for="{{ formData.id }}" class="col-sm-2 control-label">
        <i ng-if="formData.options.description.length" class="fa fa-question-circle" uib-popover="{{ formData.options.description }}"></i>
        <abbr ng-if="formData.required" title="">*</abbr>
        {{ formData.label }}
    </label>
    <div class="col-sm-10">
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value }}">
        <div class="row">
            <div ng-if="formData.value" class="col-sm-4">
                <div class="videoWrapper">
                    <iframe ng-src="{{ videoUrl() }}" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
            <div ng-class="{'col-sm-8': formData.value, 'col-sm-12': !formData.value}">
                <input type="text" class="form-control" id="{{ formData.id }}" ng-model="youtubeLink" ng-change="changeValue()">
            </div>
        </div>
        <span ng-if="formData.errors.length" class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
