<div class="file-dialog" ng-controller="LinkDialogController">
    <input type="hidden" id="linkSelection" value="{{ linkSelection }}">
    <div class="container-fluid">
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    <?= $this->translate('label.link-type-selector', 'admin') ?>
                </label>
                <div class="col-sm-10">
                    <select ng-model="linkType" class="form-control" ng-change="change()">
                        <?php foreach($this->linkTypes as $type): ?>
                            <option value="<?= $type ?>"><?= $this->translate('link-type.'.$type, 'admin')?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <hr>
            <div ng-repeat="item in includeArray">
                <div ng-include="item"></div>
            </div>
        </form>
    </div>

</div>

<?php
foreach($this->linkTypes as $type) {
    echo $this->partial('link/' . $type);
}
?>