<div class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : ''?>">
    <label for="<?= $this->element->getName() ?>" class="col-sm-2 control-label">
        <?= $this->element->getLabel() ?>
    </label>
    <?php
    $value = $this->element->getValue(false);
    if (empty($value)) {
        $value = "";
    } elseif (is_string($value)) {
        $value = new \DateTime($value);
        $value->setTimezone(new \DateTimeZone($this->admin()->getDisplayTimezone()));
        $value = $value->format("Y-m-d H:i");
    } elseif ($value instanceof \DateTime) {
        $value->setTimezone(new \DateTimeZone($this->admin()->getDisplayTimezone()));
        $value = $value->format("Y-m-d H:i");
    } else {
        $value = "";
    }
    ?>
    <div class="col-sm-10">
        <div class="input-group w-md" ng-controller="AdminDatepickerController" data-value="<?= $value ?>" data-model-name="<?= $this->admin()->generateAngularModelName($this->element->getName()) ?>">
            <input type="hidden" name="<?= $this->element->getName() ?>" value="{{ <?= $this->admin()->generateAngularModelName($this->element->getName()) ?> | datetime:'':'YYYY-MM-DD HH:mm' : 'UTC'}}">
            <input
                type="text"
                class="form-control"
                id="<?= $this->element->getName() ?>"
                data-ng-model="<?= $this->admin()->generateAngularModelName($this->element->getName()) ?>"
                data-datetime-picker="yyyy-MM-dd HH:mm"
                data-is-open="opened"
                data-datepicker-options="dateOptions"
                disabled
                >
            <span class="input-group-btn">
                <button type="button" class="btn btn-default" ng-click="open($event)">
                    <i class="fa fa-calendar"></i>
                </button>
            </span>
        </div>
        <?php if ($this->hasErrors): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
