<?php
$baseFormName = uniqid('dynamic_form/base') . '.html';

if ($this->element->getOption("compact") === true) {
    $baseFormContent = $this->partial('partial/admin42/dynamic/base-form-compact');
} else {
    $baseFormContent = $this->partial('partial/admin42/dynamic/base-form-normal');
}
?>
<?php $this->admin()->addHtmlTemplate($baseFormName, $baseFormContent) ?>

<?php
$preparedFormElements = [];
$prototypesElements = [];
?>

<?php foreach ($this->elements as $element): ?>
    <?php
    $preparedFormElementTemplateName = uniqid('dynamic_form/element/') . '.html';
    $preparedFormElements[] = [
        'deleted' => false,
        'collapsed' => false,
        'templateName' => $preparedFormElementTemplateName,
        'label' => $element['element']->getLabel(),
        'type' => $element['element']->getOption('dynamic_type'),
        'name' => $element['element']->getName(),
        'initial' => true,
        'hash' => $element['element']->getOption('hash'),
    ];
    ?>

    <?php $this->admin()->addHtmlTemplate($preparedFormElementTemplateName, $element['markup']) ?>
<?php endforeach; ?>

<?php foreach($this->templateProtoTypes as $element): ?>
    <?php
    $prototypeFormElementTemplateName = uniqid('dynamic_form/prototype/') . '.html';
    $prototypesElements[] = [
        'deleted' => false,
        'collapsed' => false,
        'templateName' => $prototypeFormElementTemplateName,
        'label' => $element['element']->getLabel(),
        'type' => $element['element']->getOption('dynamic_type'),
        'name' => $element['element']->getName(),
        'initial' => false,
        'hash' => 0,
    ];
    ?>

    <?php $this->admin()->addHtmlTemplate($prototypeFormElementTemplateName, $element['markup']) ?>
<?php endforeach; ?>

<?php
usort($prototypesElements, function ($a, $b) {
   return strcasecmp($a['label'], $b['label']);
});

$prepareFormUniqueId = uniqid('dynamic_form/prepare') . '.json';
$this->admin()->addJsonTemplate($prepareFormUniqueId, $preparedFormElements);

$prototypeFormUniqueId = uniqid('dynamic_form/prototype') . '.json';
$this->admin()->addJsonTemplate($prototypeFormUniqueId, $prototypesElements);

?>
<div base-form="<?= $baseFormName ?>" admin-dynamic-form admin-dynamic-form-elements="<?= $prepareFormUniqueId ?>" parent-hashes="parentHashes" admin-dynamic-prototypes="<?= $prototypeFormUniqueId ?>"></div>
