<?php
$jsonDataId = uniqid("linkData_");
$jsonData = [
    'linkId' => null,
    'linkType' => null,
    'linkValue' => null,
    'linkDisplayName' => null,
];

$linkId = (int) $this->element->getValue();
if ($linkId > 0) {
    $linkModel = $this->link()->getLink($linkId);
    if ($linkModel) {
        $jsonData = [
            'linkId' => $linkModel->getId(),
            'linkType' => $linkModel->getType(),
            'linkValue' => \Zend\Json\Json::decode($linkModel->getValue(), \Zend\Json\Json::TYPE_ARRAY),
            'linkDisplayName' => $this->link()->getDisplayName($linkId),
        ];
    }
}

$this->admin()->addJsonTemplate($jsonDataId, $jsonData);
?>
<div class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : ''?>">
    <label for="<?= $this->element->getName() ?>" class="col-sm-2 control-label">
        <?= $this->translate($this->element->getLabel(), 'admin') ?>
        <?php if($this->element->hasAttribute('required')): ?>
            <abbr title="required">*</abbr>
        <?php endif; ?>
    </label>
    <div class="col-sm-10" ng-controller="LinkController" data-link-save-url="<?= $this->url('admin/link') ?>" data-json-data-id="<?= $jsonDataId ?>">
        <div>
            <input type="hidden" name="<?= $this->element->getName() ?>" value="{{ linkId }}">
            <div class="input-group">
                <input type="text" class="form-control" ng-model="linkDisplayName" readonly>
                <span class="input-group-btn">
                    <a type="button" class="btn btn-default" ng-click="selectLink()">
                        <i class="fa fa-check"></i>
                        <?= $this->translate('button.select', 'admin') ?>
                    </a>
                    <a type="button" class="btn btn-default" ng-click="clearLink()">
                        <i class="fa fa-trash-o"></i>
                        <?= $this->translate('button.clear', 'admin') ?>
                    </a>
                </span>
            </div>
        </div>
        <?php if ($this->hasErrors): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>

<?php
$linkOptions = [];
foreach($this->element->getLinkTypes() as $type) {
    $linkOptions[] = '<option value="'.$type.'">'.$this->translate('link-type.'.$type, 'admin').'</option>';
}
$linkOptions = implode(PHP_EOL, $linkOptions);

$modalContent = <<<EOT
<div class="modal-header">
    <h3 class="modal-title">{$this->translate('title.link', 'admin')}</h3>
</div>
<div class="modal-body modal-scroll-body">
    <div class="container-fluid">
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    {$this->translate('label.link-type-selector', 'admin')}
                </label>
                <div class="col-sm-10">
                    <select ng-model="linkType" class="form-control" ng-change="change()">
                        {$linkOptions}
                    </select>
                </div>
            </div>
            <hr>
            <div ng-repeat="item in includeArray">
                <div ng-include="item"></div>
            </div>
        </form>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-click="ok()">
        <span class="fa fa-check"></span>
        {$this->translate('button.save', 'admin')}
    </button>
    <button class="btn btn-default" ng-click="cancel()">{$this->translate('button.cancel', 'admin')}</button>
</div>
EOT;
$this->admin()->addHtmlTemplate('linkModalSelectorContent.html', $modalContent);
?>

<?php
foreach($this->element->getLinkTypes() as $type) {
    echo $this->partial('link/' . $type);
}
?>
