<div class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : ''?>">
    <label class="col-sm-2 control-label">
        <?= $this->element->getLabel() ?>
    </label>
    <div class="col-sm-10">
        <div>
            <?= $this->formMultiCheckbox()
                ->setLabelAttributes(array('class' => 'checkbox-inline'))
                ->render($this->element)
            ?>
        </div>
        <?php if ($this->hasErrors): ?>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
