<div class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : ''?>">
    <label for="<?= $this->element->getName() ?>" class="col-sm-2 control-label">
        <?= $this->translate($this->element->getLabel(), 'admin') ?>
    </label>
    <div class="col-sm-10" ng-init="<?= $this->admin()->generateAngularModelName($this->element->getName()) ?> = '<?= $this->element->getValue() ?>'">
        <?= $this->formPassword($this->element->setAttributes(array(
            'class'         => 'form-control input-sm',
            'data-ng-model' => $this->admin()->generateAngularModelName($this->element->getName()),
            'id'            => $this->element->getName(),
        ))) ?>
        <?php if ($this->hasErrors): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
