<div class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : ''?>">
    <div class="col-sm-10 col-sm-offset-2">
        <div class="radio">
            <label>
                <?= $this->formRadio($this->element->setAttributes(array(
                    'id'            => $this->element->getName(),
                    'data-ng-model' => $this->admin()->generateAngularModelName($this->element->getName()),
                ))) ?>
            </label>

        </div>
        <?php if ($this->hasErrors): ?>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
