<?php
$jsonDataId = uniqid('form/select/') . '.json';
$values = [];
foreach ($this->element->getValueOptions() as $id => $value) {
    $values[] = [
        'id' => $id,
        'label' => $value
    ];
}
$this->admin()->addJsonTemplate($jsonDataId, $values)
?>
<div
    ng-controller="SelectController"
    init-value="<?= $this->element->getValue()?>"
    json-data-id="<?= $jsonDataId ?>"
    class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : ''?>"
    >
    <label class="col-sm-2 control-label">
        <?= $this->translate($this->element->getLabel(), 'admin') ?>
        <?php if($this->element->hasAttribute('required')): ?>
            <abbr title="required">*</abbr>
        <?php endif; ?>
    </label>
    <div class="col-sm-10">
        <input type="hidden" name="<?= $this->element->getName() ?>" value="{{ item.selected.id}}">
        <ui-select ng-model="item.selected" reset-search-input="false">
            <ui-select-match placeholder="<?= $this->translate($this->element->getLabel(), 'admin') ?>">{{$select.selected.label}}</ui-select-match>
            <ui-select-choices repeat="item in items track by $index">
                <div ng-bind-html="item.label | highlight: $select.search"></div>
            </ui-select-choices>
        </ui-select>
        <?php if ($this->hasErrors): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
