<?php
$editorOptions = \Zend\Json\Json::encode($this->element->getEditorOptions());
$jsonDataId = 'editor/' . md5($editorOptions) . '/options.json';
$this->admin()->addJsonTemplate($jsonDataId, $this->element->getEditorOptions());

?>
<div ng-controller="WysiwygController"
     ng-base-url="<?= $this->assetUrl('/assets/admin/admin42/js/tinymce') ?>"
     ng-content-css="<?= $this->assetUrl('/assets/admin/admin42/css/admin42.min.css') ?>"
     ng-file-browser="<?= $this->url('admin/file-dialog') ?>"
     ng-file-browser-titles='{"file":"Link","image":"Link","media":"Link"}'
     ng-link-save-url="<?= $this->url('admin/link') ?>"
     ng-json-data-id="<?= $jsonDataId ?>"
     class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : '' ?>">

    <label for="<?= $this->element->getName() ?>" class="col-sm-2 control-label">
        <?= $this->translate($this->element->getLabel(), 'admin') ?>
        <?php if ($this->element->hasAttribute('required')): ?>
            <abbr title="required">*</abbr>
        <?php endif; ?>
    </label>

    <div class="col-sm-10">

        <?= $this->formWysiwyg(
            $this->element->setAttributes(
                [
                    'class'              => 'form-control',
                    'data-tiny-wysiwyg'  => 'tinymceOptionsFull',
                ]
            )
        ) ?>

        <?php if ($this->hasErrors): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach ($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
