<div ng-controller="WysiwygController"
     ng-base-url="<?= $this->basePath('/assets/admin/core/js/tinymce') ?>"
     ng-content-css="<?= $this->basePath('/assets/admin/core/css/admin42.min.css') ?>"
     ng-file-browser="<?= $this->url('admin/file-dialog') ?>"
     ng-file-browser-titles='{"file":"Media & Sitemap Browser","image":"Media Browser","media":"Media Browser"}'
     class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : '' ?>">

    <label for="<?= $this->element->getName() ?>" class="col-sm-2 control-label">
        <?= $this->translate($this->element->getLabel(), 'admin') ?>
        <?php if ($this->element->hasAttribute('required')): ?>
            <abbr title="required">*</abbr>
        <?php endif; ?>
    </label>

    <div class="col-sm-10">

        <?= $this->formWysiwyg(
            $this->element->setAttributes(
                [
                    'class'                  => 'form-control',
                    'id'                     => uniqid('wysiwyg_'),
                    'data-ng-model'          => $this->admin()->generateAngularModelName($this->element->getName()),
                    'data-ng-initial'        => '',
                    'data-ui-tinymce'        => 'tinymceOptionsFull'
                ]
            )
        ) ?>

        <?php if ($this->hasErrors): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach ($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
