<?php
$id = uniqid("youtube_");
?>
<div class="form-group<?= ($this->hasErrors) ? ' has-error has-feedback' : ''?>">
    <label for="<?= $id ?>" class="col-sm-2 control-label">
        <?= $this->translate($this->element->getLabel(), 'admin') ?>
        <?php if($this->element->hasAttribute('required')): ?>
            <abbr title="required">*</abbr>
        <?php endif; ?>
    </label>
    <div class="col-sm-10">
        <youtube youtube-code="<?= $this->element->getValue() ?>">
            {{ test }}
            <input type="hidden" name="<?= $this->element->getName() ?>" ng-model="youtubeCode" value="{{ youtubeCode }}">
            <div class="row">
                <div ng-if="youtubeCode" class="col-sm-4">
                    <div class="videoWrapper">
                        <iframe ng-src="{{ videoUrl() }}" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
                <div ng-class="{'col-sm-8': youtubeCode, 'col-sm-12': !youtubeCode}">
                    <input type="text" class="form-control" id="" ng-model="youtubeLink" ng-change="changeValue()">
                </div>
            </div>
        </youtube>
        <?php if ($this->hasErrors): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
