<div class="form-group<?= (count($this->element->getMessages())) ? ' has-error has-feedback' : ''?>">
    <label for="<?= $this->element->getName() ?>" class="col-sm-2 control-label"><?= $this->label ?></label>
    <div class="col-sm-10">
        <?= $this->formPassword($this->element->setAttributes(array(
            'class'         => 'form-control',
            'id'            => $this->element->getName(),
            'placeholder'   => $this->placeholder,
        ))) ?>
        <?php if (count($this->element->getMessages())): ?>
            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            <ul class="list-unstyled text-danger">
                <?php foreach($this->element->getMessages() as $message): ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
