<fieldset>
    <legend><?= $this->element->getLabel() ?></legend>
    <div ui-sortable="sortableOptions" ng-model="elements">
        <div class="sortable-container" ng-repeat="element in elements track by $index" ng-init="parentHashes.<?= $this->element->getHashId() ?> = element.hash">
            <div class="panel panel-default" ng-class="{'marked-deleted' : element.deleted}">
                <div class="panel-heading">
                    <div class="pull-right">
                        <?php if ($this->permission('admin42')->isGranted('dynamic/manage/sort')): ?>
                        <a class="btn btn-xs btn-info panel-sort-handle">
                            <i class="fa fa-fw fa-sort"></i>
                        </a>
                        <?php endif; ?>
                        <?php if ($this->permission('admin42')->isGranted('dynamic/manage/delete')): ?>
                        <button class="btn btn-xs btn-danger" type="button" ng-click="element.deleted = !element.deleted">
                            <span ng-show="element.deleted" class="fa-stack">
                                <i class="fa fa-fw fa-trash fa-stack-1x"></i>
                                <i class="fa fa-fw fa-ban fa-stack-2x"></i>
                            </span>
                            <i ng-hide="element.deleted" class="fa fa-fw fa-trash"></i>
                        </button>
                        <?php endif; ?>
                    </div>
                    <div class="clearfix text-left">
                        <a class="btn btn-link btn-xs" ng-click="element.collapsed = !element.collapsed">
                            <i class="fa fa-fw" ng-class="{'fa-chevron-down': !element.collapsed, 'fa-chevron-right': element.collapsed}"></i>
                        </a>
                        {{ element.label }}
                    </div>
                </div>
                <div uib-collapse="element.collapsed" class="panel-body">
                    <input type="hidden" name="<?= $this->element->getName()?>[{{ element.hash }}][dynamic_index]" value="{{ $index }}">
                    <input type="hidden" name="<?= $this->element->getName()?>[{{ element.hash }}][dynamic_deleted]" ng-model="element.deleted" value="{{ element.deleted }}">
                    <input type="hidden" name="<?= $this->element->getName()?>[{{ element.hash }}][dynamic_type]" ng-model="element.type" value="{{ element.type }}">
                    <ng-include src="element.templateName"></ng-include>
                </div>
            </div>
        </div>
    </div>
</fieldset>
<?php if ($this->permission('admin42')->isGranted('dynamic/manage/add')): ?>
<div class="form-group">
    <div class="col-sm-offset-9 col-sm-2 text-right">
        <select ng-if="prototypes.length > 1" class="form-control" ng-model="data.selectedPrototype" ng-options="prototype.label for prototype in prototypes"></select>
    </div>
    <div class="col-sm-1 text-right">
        <button class="btn btn-default" ng-click="addTemplate()" type="button">
            <?= $this->translate('button.add', 'admin')?>
        </button>
    </div>
</div>
<?php endif; ?>
<div class="line line-dashed b-b line-lg pull-in"></div>
