<div class="alert-container">
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
    &times;
</button>
<p>')
        ->setMessageSeparatorString('</p><p>')
        ->setMessageCloseString('</p></div>');

if ($flash->hasCurrentInfoMessages()) {
    echo $flash->renderCurrent('info',    array('alert', 'alert-dismissable', 'alert-info'));

    $flash->clearCurrentMessagesFromNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO);
}

if ($flash->hasCurrentErrorMessages()) {
    echo $flash->renderCurrent('error',   array('alert', 'alert-dismissable', 'alert-danger'));

    $flash->clearCurrentMessagesFromNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR);
}

if ($flash->hasCurrentWarningMessages()) {
    echo $flash->renderCurrent('warning', array('alert', 'alert-dismissable', 'alert-warning'));

    $flash->clearCurrentMessagesFromNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING);
}

if ($flash->hasCurrentSuccessMessages()) {
    echo $flash->renderCurrent('success', array('alert', 'alert-dismissable', 'alert-success'));

    $flash->clearCurrentMessagesFromNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS);
}

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
</div>
