<?php
if (iterator_count($this->iterator) == 0) {
    echo '<p>&nbsp;</p>';
    return;
}
echo '<ol class="breadcrumb">';

/** @var \Core42\Navigation\Page\Page $page */
foreach ($this->iterator as $page){
    echo '<li>';

    $href = $this->navigation->getHref($page);
    $label = $this->translate($page->getOption('label'), 'admin');

    if (!empty($href)) {
        echo '<a href="'.$href.'">' . $label . '</a>';
    } else {
        echo $label;
    }

    echo '</li>';
}

echo '</ol>';
