<table id="<?= $this->name?>" class="table table-striped table-datatable">
    <thead>
        <tr>
            <?php foreach($this->dataTable as $column): ?>
            <th><?= $column->getLabel() ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
</table>
<script>
    <?php
    $settings = $this->dataTable->getAttributes();
    /** @var \Admin42\DataTable\Column\Column $column */
    foreach ($this->dataTable as $column) {
        $columnSettings = array(
            'searchable' => $column->isSearchable(),
            'sortable' => $column->isSortable()
        );
        foreach ($column->getAttributes() as $attrName => $attrValue) {
            $columnSettings[$attrName] = $attrValue;
        }

        $settings['columns'][] = $columnSettings;
    }
    ?>
    $('#<?= $this->name ?>').dataTable(<?= \Zend\Json\Json::encode(
        $settings,
        false,
        array('enableJsonExprFinder' => true))?>);
</script>
