<?php
if (iterator_count($this->iterator) == 0) {
    return;
}
$html = array();
$prevDepth = -1;

/** @var \Core42\Navigation\Page\Page $page */
foreach ($this->iterator as $page){
    $depth = $this->iterator->getDepth();
    if ($depth == $this->minDepth) {
        $prevDepth = $depth;
        continue;
    }

    if ($depth > $prevDepth) {
        if($prevDepth == $this->minDepth) {
            $html[] = '<ul class="nav">';
        } else {
            $html[] = '<ul class="nav nav-sub dk">';
        }
    } elseif($prevDepth > $depth) {
        for ($i = $prevDepth; $i > $depth; $i--) {
            $html[] = '</li></ul>';
        }
        $html[] = '</li>';
    } else {
        $html[] = '</li>';
    }

    $icon = '<i class="icon text-success"></i>';
    if (strlen($page->getOption("icon"))) {
        $icon = '<i class="icon '.$page->getOption("icon").'"></i>';
    }

    $label = $this->translate($page->getOption('label'), 'admin');

    $isActive = $this->navigation->isActive($page);
    $href = $this->navigation->getHref($page);

    if($page->hasChildren() && $depth == 0 && empty($href)) {
        $html[] = '<li class="'.(($isActive) ? " active" : "").'">';
        $html[] = '<a>';
        $html[] = '<span class="pull-right text-muted">';
        $html[] = '<i class="fa fa-fw fa-angle-right text"></i>';
        $html[] = '<i class="fa fa-fw fa-angle-down text-active"></i>';
        $html[] = '</span>';
        $html[] = $icon;
        $html[] = '<span class="font-bold">'.$label.'</span>';
        $html[] = '</a>';
    } else {
        $html[] = '<li'.(($isActive) ? ' class="active"' : "").'>';
        $html[] = '<a href="'.$href.'">'. $icon .'<span class="'.(($depth == 0) ? "font-bold" : "").'">' . $label . '</span></a>';
    }

    $prevDepth = $depth;
}

for ($i = $prevDepth+1; $i > 0; $i--) {
    $html[] = '</li></ul>';
}

echo implode(PHP_EOL, $html);
