<?php
if (iterator_count($this->iterator) == 0) {
    return;
}
$prevDepth = -1;

/** @var \Core42\Navigation\Page\Page $page */
foreach ($this->iterator as $page){
    $depth = $this->iterator->getDepth();
    if ($depth == $this->minDepth) {
        $prevDepth = $depth;
        continue;
    }

    if ($depth > $prevDepth) {
        if($prevDepth == $this->minDepth) {
            echo '<ul class="navbar-left nav navbar-nav" id="headerMenu">';
        } else {
            echo '<ul class="dropdown-menu">';
        }
    } elseif($prevDepth > $depth) {
        for ($i = $prevDepth; $i > $depth; $i--) {
            echo '</li></ul>';
        }
        echo '</li>';
    } else {
        echo '</li>';
    }

    $icon = "";
    if (strlen($page->getOption("icon"))) {
        $icon = '<span class="'.$page->getOption("icon").'"></span>&nbsp;';
    }

    if($page->hasChildren() && $prevDepth == $this->minDepth) {
        echo '<li class="dropdown">';
        echo '<a href="'.$this->navigation->getHref($page).'" class="dropdown-toggle" data-toggle="dropdown">' . $icon .$page->getOption('label') . '</a>';
    } else {
        echo '<li>';
        echo '<a href="'.$this->navigation->getHref($page).'">' . $icon . $page->getOption('label') . '</a>';
    }

    $prevDepth = $depth;
}

for ($i = $prevDepth+1; $i > 0; $i--) {
    echo '</li></ul>';
}
