<?php
if (iterator_count($this->iterator) == 0) {
    return;
}
$html = array();
$prevDepth = -1;

/** @var \Core42\Navigation\Page\Page $page */
foreach ($this->iterator as $page){
    $depth = $this->iterator->getDepth();
    if ($depth == $this->minDepth) {
        $prevDepth = $depth;
        continue;
    }

    if ($depth > $prevDepth) {
        if($prevDepth == $this->minDepth) {
            $html[] = '<ul class="navbar-left nav navbar-nav" id="headerMenu">';
        } else {
            $html[] = '<ul class="dropdown-menu">';
        }
    } elseif($prevDepth > $depth) {
        for ($i = $prevDepth; $i > $depth; $i--) {
            $html[] = '</li></ul>';
        }
        $html[] = '</li>';
    } else {
        $html[] = '</li>';
    }

    $icon = "";
    if (strlen($page->getOption("icon"))) {
        $icon = '<span class="'.$page->getOption("icon").'"></span>&nbsp;';
    }

    $label = $this->translate($page->getOption('label'), 'admin');

    $isActive = $this->navigation->isActive($page);

    if($page->hasChildren()) {
        $html[] = '<li class="dropdown'.(($isActive) ? " active" : "").'">';
        $html[] = '<a href="'.$this->navigation->getHref($page).'" class="dropdown-toggle" data-toggle="dropdown">' . $icon .$label . '</a>';
    } else {
        $html[] = '<li'.(($isActive) ? ' class="active"' : "").'>';
        $html[] = '<a href="'.$this->navigation->getHref($page).'">' . $icon . $label . '</a>';
    }

    $prevDepth = $depth;
}

for ($i = $prevDepth+1; $i > 0; $i--) {
    $html[] = '</li></ul>';
}

echo implode(PHP_EOL, $html);
