<div class="app-aside hidden-xs bg-dark dk">
    <div class="aside-wrap">
        <div class="navi-wrap">

            <ul class="nav">
                <li class="m-t-sm text-muted text-sm identity">
                    <a href="<?= $this->url('admin/user/manage') ?>">
                        <span class="m-l m-r-xs shortname-container">
                            <?= $this->auth(\Admin42\Authentication\AuthenticationService::class)->getIdentity()->getShortName() ?>
                        </span>
                        <div class="hidden-folded">
                            <div class="m-t-xs font-bold text-lt">
                                <?= $this->admin()->getUserDisplayName(
                                    $this->auth(\Admin42\Authentication\AuthenticationService::class)->getIdentity()
                                ) ?>
                            </div>
                            <div class="text-muted text-xs role">
                                <?= $this->auth(\Admin42\Authentication\AuthenticationService::class)->getIdentity()->getRole() ?>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>

            <nav ui-nav class="navi clearfix">

                <?= $this->menu('partial/admin42/main-menu', 'admin42')->enableFilter('adminPermission')->setMaxDepth(1) ?>

                <ul class="nav m-b-lg">
                    <li class="line bg-dark"></li>
                    <li class="m-b-sm text-muted" style="cursor: default;">
                        <a href="<?= !empty($this->admin()->getWhitelabelOption('sidebar-bottom-link')) ? $this->admin()
                            ->getWhitelabelOption('sidebar-bottom-link') : '#' ?>" target="_blank"
                           title="<?= $this->admin()->getWhitelabelOption('sidebar-bottom-link-title') ?>">
                            <i class="icon fa fa-fw">
                                <img class="icon icon-kiwi img-responsive inline"
                                     src="<?= $this->assetUrl($this->admin()->getWhitelabelOption('logo-xs')); ?>">
                            </i>
                            <span class="hidden-folded text-xs">
                                <?= trim($this->admin()->getWhitelabelOption('sidebar-bottom-text')) ?>
                            </span>
                        </a>
                    </li>
                </ul>
            </nav>

        </div>
    </div>
    <div class="clearfix"></div>
</div>
