<div class="app-header navbar">
    <div class="navbar-header bg-dark">
        <button class="pull-right visible-xs dk" ui-toggle-class="show" data-target=".navbar-collapse">
            <i class="glyphicon glyphicon-cog"></i>
        </button>
        <button class="pull-right visible-xs" ui-toggle-class="off-screen" data-target=".app-aside" ui-scroll-to="app">
            <i class="glyphicon glyphicon-align-justify"></i>
        </button>
        <a href="<?= $this->url('admin/home') ?>" class="navbar-brand">
            <img src="<?= $this->assetUrl($this->admin()->getWhitelabelOption('logo-icon')); ?>" class="img-responsive">
            <?php if(!empty(trim($this->admin()->getWhitelabelOption('topbar-title'))) && !empty($this->admin()->getWhitelabelOption('show-topbar-title'))): ?>
                <span class="hidden-folded m-l-xs"><?= $this->admin()->getWhitelabelOption('topbar-title') ?></span>
            <?php endif ?>
        </a>
    </div>

    <div class="collapse pos-rlt navbar-collapse bg-dark">
        <div class="nav navbar-nav hidden-xs">
            <a href class="btn no-shadow navbar-btn" ng-click="app.$storage.asideFolded = !app.$storage.asideFolded">
                <i class="fa {{app.$storage.asideFolded ? 'fa-indent' : 'fa-dedent'}} fa-fw"></i>
            </a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown" uib-dropdown>
                <a href class="dropdown-toggle clear" uib-dropdown-toggle>
                    <span class="m-r-xs shortname-container-xs">
                        <?= $this->auth(\Admin42\Authentication\AuthenticationService::class)->getIdentity()->getShortName() ?>
                    </span>
                    <span class="font-bold text-lt">
                        <?= $this->admin()->getUserDisplayName(
                            $this->auth(\Admin42\Authentication\AuthenticationService::class)->getIdentity()
                        ) ?>
                    </span>
                    <b class="caret text-lt"></b>
                </a>
                <ul class="dropdown-menu w" uib-dropdown-menu>
                    <li>
                        <a href="<?= $this->url('admin/user/manage') ?>">
                            <?= $this->translate('label.profile', 'admin') ?>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="<?= $this->url('admin/logout') ?>">
                            <?= $this->translate('label.logout', 'admin') ?>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
