<div class="app-header navbar">
    <div class="navbar-header bg-dark">
        <button class="pull-right visible-xs dk" ui-toggle-class="show" data-target=".navbar-collapse">
            <i class="glyphicon glyphicon-cog"></i>
        </button>
        <button class="pull-right visible-xs" ui-toggle-class="off-screen" data-target=".app-aside" ui-scroll-to="app">
            <i class="glyphicon glyphicon-align-justify"></i>
        </button>
        <a href="<?= $this->url('admin')?>" class="navbar-brand text-lt">
            <img src="<?= $this->basePath('assets/admin/core/images/iconkiwi42.png'); ?>" alt=".">
            <span class="hidden-folded m-l-xs font-thin">kiw<span class="text-light">i</span></span>
        </a>
    </div>

    <div class="collapse pos-rlt navbar-collapse bg-primary bg_sub_header">
        <div class="nav navbar-nav hidden-xs">
            <a href class="btn no-shadow navbar-btn" ng-click="app.settings.asideFolded = !app.settings.asideFolded">
                <i class="fa {{app.settings.asideFolded ? 'fa-indent' : 'fa-dedent'}} fa-fw"></i>
            </a>
        </div>

        <form class="navbar-form navbar-form-sm navbar-left shift" ui-shift="prependTo" target=".navbar-collapse" role="search">
            <div class="form-group">
                <div class="input-group">
                    <input type="text" ng-model="selected" typeahead="state for state in states | filter:$viewValue | limitTo:8" class="form-control input-sm bg-light no-border rounded padder" placeholder="Search ...">
                          <span class="input-group-btn">
                            <button type="submit" class="btn btn-sm bg-light rounded"><i class="fa fa-search"></i></button>
                          </span>
                </div>
            </div>
        </form>

        <ul class="nav navbar-nav navbar-right">
            <li class="hidden-xs">
                <a ui-fullscreen></a>
            </li>
            <li class="dropdown" dropdown ng-controller="NotificationController" data-notification-url="<?= $this->url('admin/api/notification/list')?>">

                <a href class="dropdown-toggle" dropdown-toggle>
                    <i class="icon-bell fa-fw"></i>
                    <span class="visible-xs-inline">Notifications</span>
                    <span class="badge badge-sm up pull-right-xs" ng-class="{'bg-danger': notifications.length > 0}">{{ notifications.length }}</span>
                </a>
                <div class="dropdown-menu w-xl animated fadeInUp">
                    <div class="panel bg-white">
                        <div class="panel-heading b-light bg-light">
                            <strong><?= sprintf($this->translate('You have %s notifications'), '{{ notifications.length }}')?></strong>
                        </div>
                        <div class="list-group">
                            <div ng-repeat="notification in notifications">
                                <a ng-href="{{notification.link}}" class="media list-group-item">
                                    <span class="media-body block m-b-none">
                                      {{notification.text}}<br>
                                      <small class="text-muted">{{notification.created}}</small>
                                    </span>
                                </a>
                            </div>
                        </div>
                        <div ng-if="notifications.length > 0" class="panel-footer text-sm">
                            <a href ng-click="clearNotifications('<?= $this->url('admin/api/notification/clear')?>')" class="pull-right">
                                <i class="fa fa-trash"></i>
                            </a>
                            <a href ng-click="clearNotifications('<?= $this->url('admin/api/notification/clear')?>')" data-toggle="class:show animated fadeInRight">
                                Clear all the notifications
                            </a>
                        </div>
                    </div>
                </div>
            </li>
            <li class="dropdown" dropdown>
                <a href class="dropdown-toggle clear" dropdown-toggle>
                        <span class="hidden-sm hidden-md">
                            <?= $this->admin()->getUserDisplayName($this->auth('Admin42\Authentication')->getIdentity()) ?>
                        </span> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu animated fadeInRight w">
                    <li>
                        <a href="<?= $this->url('admin/user/manage')?>">
                            <?= $this->translate('label.profile', 'admin')?>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            Help
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="<?= $this->url('admin/logout')?>">
                            <?= $this->translate('label.logout', 'admin')?>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
