<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-user"></span>
        <?php
        $label = $this->params()->fromRoute('isEditMode') == true ? 'title.user-edit' : 'title.user-add';
        ?>
        <?= $this->translate($label, 'admin') ?>
    </h1>
</div>
<div class="wrapper-md">
    <form class="form-horizontal" role="form" action="<?= $this->url(null, array(), array(), true) ?>" method="post">
        <div class="panel b-a">
            <div class="panel-body">
                <?= $this->form($this->createEditForm)?>
            </div>
            <div class="panel-footer">
                <div class="form-group">
                    <div class="col-sm-offset-2 col-md-10">
                        <button type="submit" class="btn btn-success">
                            <span class="fa fa-save"></span>
                            <?= $this->translate('button.save', 'admin') ?>
                        </button>

                        <?php if($this->params()->fromRoute('isEditMode') == true && $this->permission('admin42')->isGranted('route/admin/user/delete')): ?>
                            <delete
                                url="<?= $this->url('admin/user/delete') ?>"
                                title="<?= $this->translate("user.modal.delete.title", "admin") ?>"
                                content="<?= $this->translate("user.modal.delete.content", "admin") ?>"
                                request-id="<?= $this->params()->fromRoute("id") ?>"
                                >
                            </delete>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
