<div class="panel panel-default">
    <div class="panel-heading">
        <span class="fa fa-users"></span>
        <?= $this->translate('title.users', 'admin') ?>
    </div>
    <?= $this->dataTable($this->dataTable) ?>
    <div class="panel-footer">
        <a class="btn btn-default" href="<?= $this->url('admin/user/add') ?>">
            <span class="fa fa-plus-circle"></span>
            <?= $this->translate('button.user-add', 'admin') ?>
        </a>
    </div>
</div>
