<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-users"></span>
        <?= $this->translate('title.users', 'admin') ?>
    </h1>
</div>
<div class="wrapper-md">
    <div class="panel panel-default">
        <div class="table-responsive" ng-controller="DataGridController" data-url="<?= $this->url()?>">
            <table st-table="collection"  st-pipe="callServer" class="table table-striped top-border-radius">
                <thead>
                <tr>
                    <th width="5%" st-sort="id"><?= $this->translate('field.id', 'admin') ?></th>
                    <th width="15%" st-sort="email"><?= $this->translate('field.email', 'admin') ?></th>
                    <th width="15%" st-sort="username"><?= $this->translate('field.username', 'admin') ?></th>
                    <th width="15%" st-sort="displayName"><?= $this->translate('field.display-name', 'admin') ?></th>
                    <th width="10%"><?= $this->translate('field.role', 'admin') ?></th>
                    <th width="15%" st-sort="created"><?= $this->translate('field.created', 'admin') ?></th>
                    <th width="15%" st-sort="lastLogin"><?= $this->translate('field.last-login', 'admin') ?></th>
                    <th></th>
                </tr>
                <tr>
                    <th>
                        <input st-search="id" class="form-control input-sm" type="text"/>
                    </th>
                    <th>
                        <input st-search="email" placeholder="<?= $this->translate('search.email', 'admin') ?>" class="form-control input-sm" type="text"/>
                    </th>
                    <th>
                        <input st-search="username" placeholder="<?= $this->translate('search.username', 'admin') ?>" class="form-control input-sm" type="text"/>
                    </th>
                    <th>
                        <input st-search="displayName" placeholder="<?= $this->translate('search.display-name', 'admin') ?>" class="form-control input-sm" type="text"/>
                    </th>
                    <th colspan="3">
                    </th>
                    <th class="text-right vertical-middle">
                        <i class="fa fa-fw fa-search"></i>
                    </th>
                </tr>
                </thead>
                <tbody ng-hide="isLoading">
                    <tr ng-repeat="row in collection">
                        <td class="text-right vertical-middle"><code>#{{row.id}}</code></td>
                        <td class="vertical-middle">{{row.email}}</td>
                        <td class="vertical-middle">{{row.username}}</td>
                        <td class="vertical-middle">{{row.displayName}}</td>
                        <td class="vertical-middle"><span class="label label-success">{{row.role}}</span></td>
                        <td class="vertical-middle"><small>{{row.created | datetime}}</small></td>
                        <td class="vertical-middle"><small>{{row.lastLogin | datetime}}</small></td>
                        <td class="vertical-middle text-right">
                            <?php if($this->permission('admin42')->isGranted('route/admin/user/edit')): ?>
                            <a class="btn btn-info btn-xs" ng-href="<?= $this->url("admin/user/edit", ['id' => "{{ row.id }}"])?>">
                                <span class="fa fa-pencil" aria-hidden="true"></span>
                            </a>
                            <?php endif; ?>
                            <?php if($this->permission('admin42')->isGranted('route/admin/user/delete')): ?>
                            <delete
                                url="<?= $this->url('admin/user/delete') ?>"
                                title="<?= $this->translate("user.modal.delete.title", "admin") ?>"
                                size="xs"
                                content="<?= $this->translate("user.modal.delete.content", "admin") ?>"
                                request-id="{{row.id}}"
                                >
                            </delete>
                            <?php endif; ?>
                        </td>
                    </tr>
                </tbody>
                <tbody ng-show="isLoading">
                    <tr>
                        <td colspan="8" class="text-center"><i class="fa fa-spin fa-refresh"></i></td>
                    </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="8" class="text-center">
                        <div st-pagination="" st-items-by-page="10" st-displayed-pages="10"></div>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="panel-footer">
            <?php if($this->permission('admin42')->isGranted('route/admin/user/add')): ?>
            <a class="btn btn-default" href="<?= $this->url('admin/user/add') ?>">
                <span class="fa fa-plus-circle"></span>
                <?= $this->translate('button.user-add', 'admin') ?>
            </a>
            <?php endif; ?>
        </div>
    </div>
</div>
