<?php
$this->loginForm->prepare();
?>
<div class="login-container container w-xxl w-auto-xs">
    <div id="login-header">
        <img class="img-responsive" src="<?= $this->assetUrl($this->admin()->getWhitelabelOption('logo-lg')); ?>" id="logo" border="0" alt="kiwi42">
    </div>
    <!--<div id="login-subheader" class="subheader bold color-1"><h4>Login</h4></div>-->
    <div class="panel">
        <div class="panel-body">
            <form role="form" class="form-horizontal" method="post" action="<?= $this->url() ?>">
                <?= $this->formRow($this->loginForm->get('csrf')) ?>
                <div class="form-group<?= (count($this->loginForm->get('identity')->getMessages()))
                    ? ' has-error has-feedback' : '' ?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-user fa-fw"></span>
                            </span>
                            <?= $this->formInput(
                                $this->loginForm->get('identity')->setAttributes(
                                    [
                                        'class'       => 'form-control',
                                        'placeholder' => $this->translate(
                                            $this->loginForm->get('identity')->getLabel(),
                                            'admin'
                                        )
                                    ]
                                )
                            ) ?>
                        </div>
                        <?php if (count($this->loginForm->get('identity')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach ($this->loginForm->get('identity')->getMessages() as $message): ?>
                                    <li><?= $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-group<?= (count($this->loginForm->get('password')->getMessages()))
                    ? ' has-error has-feedback' : '' ?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-lock fa-fw"></span>
                            </span>
                            <?= $this->formPassword(
                                $this->loginForm->get('password')->setAttributes(
                                    [
                                        'class'       => 'form-control',
                                        'placeholder' => $this->translate(
                                            $this->loginForm->get('password')->getLabel(),
                                            'admin'
                                        )
                                    ]
                                )
                            ) ?>
                        </div>
                        <?php if (count($this->loginForm->get('password')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach ($this->loginForm->get('password')->getMessages() as $message): ?>
                                    <li><?= $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-group no-margin">
                    <div class="col-sm-12 text-center">
                        <button type="submit" class="btn btn-block btn-primary btn-addon">
                            <i class="fa fa-sign-in"></i>
                            <?= $this->translate('button.login', 'admin') ?>
                        </button>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12 m-t-sm">
                        <a href="<?= $this->url('admin/lost-password') ?>">
                            <?= $this->translate('button.lost-password', 'admin') ?>
                        </a>
                    </div>
                </div>

            </form>
        </div>
    </div>
    <div class="box-bottom"></div>
</div>
<div class="bottomline">
    <a href="<?= !empty($this->admin()->getWhitelabelOption('sidebar-bottom-link')) ? $this->admin()->getWhitelabelOption('sidebar-bottom-link') : '#' ?>" target="_blank" title="<?= $this->admin()->getWhitelabelOption('sidebar-bottom-link-title') ?>">
        <small class="text-muted">
            <img class="icon icon-kiwi img-responsive inline" src="<?= $this->assetUrl($this->admin()->getWhitelabelOption('logo-xs-dark')); ?>"><br>
            <?= trim($this->admin()->getWhitelabelOption('sidebar-bottom-text')) ?>
        </small>
    </a>
</div>
