<?php
$this->loginForm->prepare();
?>
<div class="container-fluid" id="login">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-md-offset-4 col-lg-offset-4">
            <div id="logo" class="logo-lg-t"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-md-offset-4 col-lg-offset-4">
            <div class="panel">

                <div class="panel-heading">
                    <b>Login</b>
                </div>
                <div class="panel-body">
                    <form role="form" action="<?= $this->url() ?>" method="post" class="form-horizontal">
                        <?= $this->formElementRender($this->loginForm->get('username'), 'partial/form/text', array(
                            'label'         => 'Username',
                            'placeholder'   => 'Enter Username',
                        )) ?>

                        <?= $this->formElementRender($this->loginForm->get('password'), 'partial/form/password', array(
                            'label'         => 'Password',
                            'placeholder'   => 'Password',
                        )) ?>
                        <div class="clearfix"></div>
                        <a href="#" class="pull-left"><small>Forgot Passwort</small></a>
                        <button type="submit" class="btn btn-default pull-right">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
