<?php
$this->lostPasswordForm->prepare();
?>
<div class="login-container container w-xxl w-auto-xs">
    <div id="login-header">
        <img src="<?= $this->basePath($this->admin()->getWhitelabelOption('logo-lg')); ?>" id="logo" border="0" alt="kiwi42">
    </div>
    <div class="panel">
        <div class="panel-body">
            <p class="text-left">
                <?= $this->translate('text.lostpw-description', 'admin' ) ?>
            </p>
            <form role="form" class="form-horizontal" method="post" action="<?= $this->url() ?>">
                <?= $this->formRow($this->lostPasswordForm->get('csrf')) ?>
                <div class="form-group<?= (count($this->lostPasswordForm->get('email')->getMessages())) ? ' has-error has-feedback' : ''?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-envelope fa-fw"></span>
                            </span>
                            <?= $this->formInput($this->lostPasswordForm->get('email')->setAttributes(array(
                                'class'         => 'form-control',
                                'placeholder'   => $this->translate($this->lostPasswordForm->get('email')->getLabel(), 'admin')
                            ))) ?>
                        </div>
                        <?php if (count($this->lostPasswordForm->get('email')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach($this->lostPasswordForm->get('email')->getMessages() as $message): ?>
                                    <li><?= $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="col-sm-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary pull-left">
                            <span class="fa fa-mail-forward"></span>
                            <?= $this->translate('button.recover-password', 'admin')?>
                        </button>

                        <a href="<?= $this->url('admin/login')?>" class="pull-right btn btn-default">
                            <?= $this->translate('button.cancel', 'admin') ?>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="bottomline">
    <small>
        kiwi42&nbsp;&copy;&nbsp;<a href="http://www.raum42.at" target="_blank" title="raum42 OG">raum42 OG</a><br/>
        <img src="<?= $this->basePath('assets/admin/core/images/logo-xs.png') ?>">
    </small>
</div>
