<?php
$this->lostPasswordForm->prepare();
?>
<div class="container-fluid" id="login">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-md-offset-4 col-lg-offset-4">
            <div id="logo" class="logo-lg-t"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-md-offset-4 col-lg-offset-4">
            <div class="panel">
                <div class="panel-body">
                    <?php if (count($this->lostPasswordForm->getMessages()) > 0): ?>
                        <div class="alert alert-danger" role="alert">
                            An error occured
                        </div>
                    <?php else: ?>
                        <p class="text-center">
                            <?= $this->translate('text.lostpw-description', 'admin' ) ?>
                        </p>
                    <?php endif; ?>
                    <form role="form" class="form-horizontal" method="post" action="<?= $this->url() ?>">
                        <?= $this->formElementRender($this->lostPasswordForm->get('csrf')) ?>
                        <div class="form-group<?= (count($this->lostPasswordForm->get('email')->getMessages())) ? ' has-error has-feedback' : ''?>">
                            <div class="col-sm-12">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <span class="fa fa-envelope fa-fw"></span>
                                    </span>
                                    <?= $this->formInput($this->lostPasswordForm->get('email')->setAttributes(array(
                                        'class'         => 'form-control',
                                        'placeholder'   => $this->translate($this->lostPasswordForm->get('email')->getLabel(), 'admin')
                                    ))) ?>
                                </div>
                                <?php if (count($this->lostPasswordForm->get('email')->getMessages())): ?>
                                    <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                                    <ul class="list-unstyled text-danger">
                                        <?php foreach($this->lostPasswordForm->get('email')->getMessages() as $message): ?>
                                            <li><?= $message ?></li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-primary pull-left">
                                    <span class="fa fa-mail-forward"></span>
                                    <?= $this->translate('button.recover-password', 'admin')?>
                                </button>
                                <a href="<?= $this->url('admin/login')?>" class="btn btn-default pull-right">
                                    <?= $this->translate('button.cancel', 'admin') ?>
                                </a>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <small>
                        &copy; raum42 OG
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
