<?php
$this->lostPasswordForm->prepare();
?>
<div class="login-container container w-xxl w-auto-xs">
    <div id="login-header">
        <img class="img-responsive" src="<?= $this->assetUrl($this->whitelabel()->getLogoLg()); ?>" id="logo" border="0" alt="kiwi42">
    </div>
    <div class="panel">
        <div class="panel-body">
            <p class="text-left">
                <?= $this->translate('text.lostpw-description', 'admin' ) ?>
            </p>
            <form role="form" class="form-horizontal" method="post" action="<?= $this->url() ?>">
                <?= $this->formRow($this->lostPasswordForm->get('csrf')) ?>
                <div class="form-group<?= (count($this->lostPasswordForm->get('email')->getMessages())) ? ' has-error has-feedback' : ''?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-envelope fa-fw"></span>
                            </span>
                            <?= $this->formEmail($this->lostPasswordForm->get('email')) ?>
                        </div>
                        <?php if (count($this->lostPasswordForm->get('email')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach($this->lostPasswordForm->get('email')->getMessages() as $message): ?>
                                    <li><?= $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="col-sm-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary pull-left btn-addon">
                            <i class="fa fa-mail-forward"></i>
                            <?= $this->translate('button.recover-password', 'admin')?>
                        </button>

                        <a href="<?= $this->url('admin/login')?>" class="pull-right btn btn-default">
                            <?= $this->translate('button.cancel', 'admin') ?>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="box-bottom"></div>
</div>
<div class="bottomline">
    <a href="<?= !empty($this->whitelabel()->getSidebarBottomLink()) ? $this->whitelabel()->getSidebarBottomLink() : '#' ?>" target="_blank" title="<?= $this->whitelabel()->getSidebarBottomLinkTitle() ?>">
        <small class="text-muted">
            <img class="icon icon-kiwi img-responsive inline" src="<?= $this->assetUrl($this->whitelabel()->getLogoXsDark()); ?>"><br>
            <?= trim($this->whitelabel()->getSidebarBottomText()) ?>
        </small>
    </a>
</div>
