<?= $this->pageHeader($this->translate('title.user-manage', 'admin'), 'fa fa-user') ?>
<div class="wrapper-md">
    <form class="form-horizontal" role="form" action="<?= $this->url() ?>" method="post">

        <div class="panel panel-default">
            <div class="panel-body">
                <?= $this->form($this->manageForm)?>
            </div>
            <div class="panel-footer">
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-2">
                        <submit submit-text="<?= $this->translate('button.save', 'admin') ?>"></submit>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
