<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                <span class="glyphicon glyphicon-user"></span>
                Manage your Account
            </h1>
        </div>
        <form action="<?= $this->url() ?>" method="post" role="form" class="form-horizontal">
            <div class="panel-body">
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">Username</label>
                    <div class="col-sm-10">
                        <input type="text" name="username" class="form-control" id="username" value="thomas" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                    </div>
                </div>
                <div class="form-group">
                    <label for="passwordRepeat" class="col-sm-2 control-label">Password (repeat)</label>
                    <div class="col-sm-10">
                        <input type="password" name="passwordRepeat" class="form-control" id="passwordRepeat" placeholder="Password (repeat)">
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-2">
                        <button type="submit" class="btn btn-primary">
                            Save
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
