<div class="wrapper-md">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-md-offset-3">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <?= $this->translate('permission-denied', 'admin') ?>
                </div>
                <div class="panel-body">
                    <?= $this->translate('permission-denied.content', 'admin') ?>
                </div>
            </div>
        </div>
    </div>
</div>
