<?php
$this->recoverPasswordForm->prepare();
?>
<div class="login-container container w-xxl w-auto-xs">
    <div id="login-header">
        <img class="img-responsive" src="<?= $this->assetUrl($this->whitelabel()->getLogoLg()); ?>" id="logo" border="0" alt="kiwi42">
    </div>
    <div class="panel">
        <div class="panel-body">
            <?php if (count($this->recoverPasswordForm->getMessages()) > 0): ?>
                <div class="alert alert-danger" role="alert">
                    An error occured
                </div>
            <?php endif; ?>
            <form role="form" class="form-horizontal" method="post" action="<?= $this->url(null, [], [], true) ?>">
                <?= $this->formRow($this->recoverPasswordForm->get('csrf')) ?>
                <div class="form-group<?= (count($this->recoverPasswordForm->get('password')->getMessages())) ? ' has-error has-feedback' : ''?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-lock fa-fw"></span>
                            </span>
                            <?= $this->formPassword($this->recoverPasswordForm->get('password')) ?>
                        </div>
                        <?php if (count($this->recoverPasswordForm->get('password')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach($this->recoverPasswordForm->get('password')->getMessages() as $message): ?>
                                    <li><?= $this->escapeHtml($message) ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-group<?= (count($this->recoverPasswordForm->get('passwordRepeat')->getMessages())) ? ' has-error has-feedback' : ''?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-lock fa-fw"></span>
                            </span>
                            <?= $this->formPassword($this->recoverPasswordForm->get('passwordRepeat')) ?>
                        </div>
                        <?php if (count($this->recoverPasswordForm->get('passwordRepeat')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach($this->recoverPasswordForm->get('passwordRepeat')->getMessages() as $message): ?>
                                    <li><?= $this->escapeHtml($message) ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="col-sm-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary pull-left btn-addon">
                            <i class="fa fa-save"></i>
                            <?= $this->translate('button.set-password', 'admin') ?>
                        </button>

                        <a href="<?= $this->url('admin/login')?>" class="pull-right btn btn-default">
                            <?= $this->translate('button.cancel', 'admin') ?>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="box-bottom"></div>
</div>
<div class="bottomline">
    <a href="<?= !empty($this->whitelabel()->getSidebarBottomLink()) ? $this->whitelabel()->getSidebarBottomLink() : '#' ?>" target="_blank" title="<?= $this->whitelabel()->getSidebarBottomLinkTitle() ?>">
        <small class="text-muted">
            <img class="icon icon-kiwi img-responsive inline" src="<?= $this->assetUrl($this->whitelabel()->getLogoXsDark()); ?>"><br>
            <?= trim($this->whitelabel()->getSidebarBottomText()) ?>
        </small>
    </a>
</div>
