<?php
$this->recoverPasswordForm->prepare();
?>
<div class="container w-xxl w-auto-xs">
    <div class="panel">
        <div class="panel-body">
            <?php if (count($this->recoverPasswordForm->getMessages()) > 0): ?>
                <div class="alert alert-danger" role="alert">
                    An error occured
                </div>
            <?php endif; ?>
            <form role="form" class="form-horizontal" method="post" action="<?= $this->url(null, array(), array(), true) ?>">
                <?= $this->formRow($this->recoverPasswordForm->get('csrf')) ?>
                <div class="form-group<?= (count($this->recoverPasswordForm->get('password')->getMessages())) ? ' has-error has-feedback' : ''?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-lock fa-fw"></span>
                            </span>
                            <?= $this->formInput($this->recoverPasswordForm->get('password')->setAttributes(array(
                                'class'         => 'form-control',
                                'placeholder'   => $this->translate($this->recoverPasswordForm->get('password')->getLabel(), 'admin')
                            ))) ?>
                        </div>
                        <?php if (count($this->recoverPasswordForm->get('password')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach($this->recoverPasswordForm->get('password')->getMessages() as $message): ?>
                                    <li><?= $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-group<?= (count($this->recoverPasswordForm->get('passwordRepeat')->getMessages())) ? ' has-error has-feedback' : ''?>">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="fa fa-lock fa-fw"></span>
                            </span>
                            <?= $this->formPassword($this->recoverPasswordForm->get('passwordRepeat')->setAttributes(array(
                                'class'         => 'form-control',
                                'placeholder'   => $this->translate($this->recoverPasswordForm->get('passwordRepeat')->getLabel(), 'admin')
                            ))) ?>
                        </div>
                        <?php if (count($this->recoverPasswordForm->get('passwordRepeat')->getMessages())): ?>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                            <ul class="list-unstyled text-danger">
                                <?php foreach($this->recoverPasswordForm->get('passwordRepeat')->getMessages() as $message): ?>
                                    <li><?= $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-primary btn-block">
                            <span class="fa fa-save"></span>
                            <?= $this->translate('button.set-password', 'admin') ?>
                        </button>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <a href="<?= $this->url('admin/login')?>" class="btn btn-default btn-block">
                            <?= $this->translate('button.cancel', 'admin') ?>
                        </a>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel-footer">
            <small>
                &copy; raum42 OG
            </small>
        </div>
    </div>
</div>
