<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa <?= $this->icon ?>"></span>
        <?php
        $label = $this->params()->fromRoute('isEditMode') == true ? 'Edit' : 'Add';
        ?>
        <?= $this->translate($label, 'admin') ?>
    </h1>
</div>
<div class="wrapper-md">
    <div class="row">
        <div class="col-lg-6">
            <form class="form-horizontal" role="form" action="<?= $this->url(null, array(), array(), true) ?>" method="post">
                <div class="panel b-a">
                    <div class="panel-body">
                        <?= $this->form($this->createEditForm)?>
                    </div>
                    <div class="panel-footer">
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-md-10">
                                <submit submit-text="<?= $this->translate('button.save', 'admin') ?>"></submit>
                                <?php if ($this->params()->fromRoute('isEditMode') == true): ?>
                                    <delete
                                        url="<?= $this->url($this->deleteRoute) ?>"
                                        title="<?= $this->translate("item.modal.delete.title", "admin") ?>"
                                        content="<?= $this->translate("item.modal.delete.content", "admin") ?>"
                                        request-id="<?= $this->params()->fromRoute("id") ?>"
                                        method="post"
                                        >
                                    </delete>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
