<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta charset="utf-8">
	<?= 
	    $this->assetJs() 
	        ->add('PackageManager42', 'jquery-1.9.1.min.js')
	        ->add('PackageManager42', 'bootstrap.min.js')
	        ->setName('admin.js')
	?>
	
	<?=
        $this->assetCss()
            ->addLess('PackageManager42', 'bootstrap.less')
            ->addLess('PackageManager42', 'responsive.less')
            ->setName('admin.css')
	?>
	
</head>
<body>
    <?= $this->content ?>
</body>
</html>
