<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?= $this->headLink() ?>

    <?= $this->headScript() ?>

    <script>
        <?= $this->admin()->angularBootstrap() ?>
    </script>
</head>

<body ng-controller="AppController" ng-cloak>

<div class="app dialog" id="app">
    <div class="fade-in-right-big smooth">
        <?= $this->content ?>
    </div>
</div>

<?= $this->admin()->getJsonTemplates() ?>
</body>

</html>
