<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?= $this->headLink() ?>

    <?= $this->headScript() ?>

    <script>
        <?= $this->admin()->angularBootstrap() ?>
    </script>
</head>

<body ng-controller="AppController">

<div class="app app-header-fixed app-aside-fixed" id="app" ng-class="{'app-aside-folded':app.settings.asideFolded}">

    <?= $this->partial('partial/admin42/topbar') ?>

    <?= $this->partial('partial/admin42/sidebar') ?>

    <div class="app-content">
        <a href class="off-screen-toggle hide" ui-toggle-class="off-screen" data-target=".app-aside" ></a>
        <div class="app-content-body fade-in-up">
            <?= $this->content ?>

        </div>
    </div>
</div>
</body>

</html>
