<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none">

    <?= $this->partial('partial/admin42/headers') ?>

    <?= $this->headLink() ?>

    <?= $this->headScript() ?>

    <script nonce="<?= $this->csp()->getNonce() ?>">
        <?= $this->angular()->angularBootstrap() ?>
    </script>
</head>

<body ng-controller="AppController" ng-cloak>

<div class="app app-header-fixed app-aside-fixed" id="app">
    <div class="fade-in-right-big smooth">
        <?= $this->content ?>

    </div>
</div>

<?= $this->angular()->getHtmlTemplates() ?>

<?= $this->angular()->getJsonTemplates() ?>

<?= $this->inlineScript() ?>

</body>

</html>
