<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="<?= $this->basePath("/static/admin/css/styles.min.css") ?>" rel="stylesheet">
    <script src="<?= $this->basePath("/static/admin/js/fruit42-admin42.min.js") ?>"></script>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <?= $this->content ?>

        </div>
    </div>
</body>

</html>
