<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" sizes="57x57" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-57x57.png') ?>">
    <link rel="apple-touch-icon" sizes="60x60" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-60x60.png') ?>">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-72x72.png') ?>">
    <link rel="apple-touch-icon" sizes="76x76" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-76x76.png') ?>">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-114x114.png') ?>">
    <link rel="apple-touch-icon" sizes="120x120" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-120x120.png') ?>">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-144x144.png') ?>">
    <link rel="apple-touch-icon" sizes="152x152" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-152x152.png') ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->basePath('assets/admin/core/images/favicon/apple-touch-icon-180x180.png') ?>">
    <link rel="icon" type="image/png" href="<?= $this->basePath('assets/admin/core/images/favicon/favicon-32x32.png') ?>" sizes="32x32">
    <link rel="icon" type="image/png" href="<?= $this->basePath('assets/admin/core/images/favicon/android-chrome-192x192.png') ?>" sizes="192x192">
    <link rel="icon" type="image/png" href="<?= $this->basePath('assets/admin/core/images/favicon/favicon-96x96.png') ?>" sizes="96x96">
    <link rel="icon" type="image/png" href="<?= $this->basePath('assets/admin/core/images/favicon/favicon-16x16.png') ?>" sizes="16x16">
    <link rel="manifest" href="<?= $this->basePath('assets/admin/core/images/favicon/manifest.json') ?>">
    <link rel="mask-icon" href="<?= $this->basePath('assets/admin/core/images/favicon/safari-pinned-tab.svg') ?>" color="#5bbad5">
    <link rel="shortcut icon" href="<?= $this->basePath('assets/admin/core/images/favicon/favicon.ico') ?>">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="<?= $this->basePath('assets/admin/core/images/favicon/mstile-144x144.png') ?>">
    <meta name="msapplication-config" content="<?= $this->basePath('assets/admin/core/images/favicon/browserconfig.xml') ?>">
    <meta name="theme-color" content="#ffffff">

    <?= $this->headLink() ?>

    <?= $this->headScript() ?>

    <script>
        <?= $this->admin()->angularBootstrap() ?>
    </script>
</head>

<body ng-controller="AppController" ng-cloak>

<div class="app app-header-fixed app-aside-fixed" id="app">
    <div class="fade-in-right-big smooth">
        <?= $this->content ?>

    </div>
</div>

<?= $this->admin()->getHtmlTemplates() ?>

<?= $this->admin()->getJsonTemplates() ?>
</body>

</html>
