<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none">

    <?= $this->headTitle()->setSeparator('::')->prepend($this->whitelabel()->getTitle()) ?>

    <link rel="apple-touch-icon" sizes="57x57" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-57x57.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="60x60" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-60x60.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-72x72.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="76x76" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-76x76.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-114x114.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="120x120" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-120x120.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-144x144.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="152x152" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-152x152.png', 'admin42') ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->assetUrl('/images/favicon/apple-touch-icon-180x180.png', 'admin42') ?>">
    <link rel="icon" type="image/png" href="<?= $this->assetUrl('/images/favicon/favicon-32x32.png', 'admin42') ?>" sizes="32x32">
    <link rel="icon" type="image/png" href="<?= $this->assetUrl('/images/favicon/android-chrome-192x192.png', 'admin42') ?>" sizes="192x192">
    <link rel="icon" type="image/png" href="<?= $this->assetUrl('/images/favicon/favicon-96x96.png', 'admin42') ?>" sizes="96x96">
    <link rel="icon" type="image/png" href="<?= $this->assetUrl('/images/favicon/favicon-16x16.png', 'admin42') ?>" sizes="16x16">
    <link rel="manifest" href="<?= $this->assetUrl('/images/favicon/manifest.json', 'admin42') ?>">
    <link rel="mask-icon" href="<?= $this->assetUrl('/images/favicon/safari-pinned-tab.svg', 'admin42') ?>" color="#5bbad5">
    <link rel="shortcut icon" href="<?= $this->assetUrl('/images/favicon/favicon.ico', 'admin42') ?>">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="<?= $this->assetUrl('/images/favicon/mstile-144x144.png', 'admin42') ?>">
    <meta name="msapplication-config" content="<?= $this->assetUrl('/images/favicon/browserconfig.xml', 'admin42') ?>">
    <meta name="theme-color" content="#ffffff">

    <?= $this->headLink() ?>

    <?= $this->headScript() ?>

    <script nonce="<?= $this->csp()->getNonce() ?>">
        <?= $this->angular()->angularBootstrap() ?>

        <?= $this->admin()->flashMessenger() ?>
    </script>

    <?= $this->partial('partial/admin42/delete-template') ?>
    <?= $this->partial('partial/admin42/submit-template') ?>
</head>

<body ng-controller="AppController" ng-cloak>

<div class="app app-header-fixed app-aside-fixed bg_body" id="app" ng-class="{'app-aside-folded':app.$storage.asideFolded}">

    <?= $this->partial('partial/admin42/topbar') ?>

    <?= $this->partial('partial/admin42/sidebar') ?>

    <div class="app-content">
        <a href class="off-screen-toggle hide" ui-toggle-class="off-screen" data-target=".app-aside" ></a>
        <div class="app-content-body" ng-class="{'app-content-full' : app.appContentFull, 'h-full' : app.appContentFull}">
            <?= $this->content ?>

        </div>
    </div>

    <div class="app-footer hide"></div>

    <toaster-container toaster-options="{'position-class': 'toast-top-right', 'close-button':true}"></toaster-container>
</div>

<?= $this->angular()->getHtmlTemplates() ?>

<?= $this->angular()->getJsonTemplates() ?>

<?= $this->inlineScript() ?>

</body>

</html>
