<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?= $this->headLink() ?>

    <?= $this->headScript() ?>

</head>

<body>

<div id="main-container" class="container-fluid">
    <div class="row">
            <div class="col-md-12">
                <?= $this->content ?>
            </div>
    </div>
</div>

</body>

</html>
