<div ng-controller="LinkExternController">
<label class="col-sm-2 control-label">
        <?= $this->translate('link-type.external', 'admin') ?>
</label>
<div class="col-sm-2">
    <select ng-model="externType" class="form-control" ng-change="change()">
        <option value="http://">http://</option>
        <option value="https://">https://</option>
        <option value="mailto:">mailto</option>
    </select>
</div>
<div class="col-sm-8">
    <input type=text class="form-control" ng-model="externUrl" ng-change="change()">
</div>
</div>
